### PR TITLE
Don't return thumbs of password-protected subalbums

### PR DESCRIPTION
**Pull request by kamil4**
Server-side fix for #139

This basically duplicates the condition from `AlbumFunctions::prepare_albums()`, only this time for subalbums, and in a less round-about way :smirk:

### CODE REVIEW

**Comment by ildyria** [comment]
It is slightly more complex, you also need to consider whether the user is an admin or a regular user and if the sub album is shared with that regular user...

**Comment by kamil4** [comment]
I played with it a bit and you are correct. In multi-user mode, it does not work correctly (the password protection is, basically, ignored). I thought the condition may be too simple, which is exactly why I spelled out where I copied it from. :smiley:

Making the multi-user mode work robustly will be a lot more work, though. There seem to be a lot of cases that are not handled correctly at the moment. E.g., the front end seems to think that a regular user can edit any public album, irrespective of who owns it (the server seems to enforce user separation, but the front end gets rather confused when uploads or deletes fail)... I've also seen weird behavior when moving photos between shared albums.

What I'm trying to say is: can we consider the fixing of passwords in multi-user mode be a separate problem, to be addressed after (or while) general multi-user support is made more robust? We could keep the issue #139 open to remind us that there are other cases that need fixing but, in the mean time, I believe the patches I submitted do correctly fix the publicMode case (hopefully without introducing any new problems).

**Comment by kamil4** [comment]
The front end side https://github.com/LycheeOrg/Lychee-front/pull/51 needs to be merged as well to complete the fix... While github gives me permission to do the merge now (and @d7415 has OK'ed the change), I wasn't sure how you want to handle such merges policy-wise so I chose to wait. If it's OK for me to merge approved PRs, should I be choosing "Squash and merge"?

FYI, I am interested in working on a comprehensive set of fixes to close the majority of such corner cases and unexpected interactions between the server and the front end, once I complete a few smaller projects. I think the first step should be documenting the current behavior to ensure that everybody is on the same page with respect to how things work and also how they are _supposed_ to work, before doing any major hacking. Where should such discussions go? The outcomes should probably end up as a set of issues but I'm not sure if starting the discussion within an issue is the right approach?

**Comment by d7415** [comment]
I was waiting for @ildyria's review on -front. I only gave a cursory look and checked that it didn't break v3.

In general terms, yes, so long as everyone's happy feel free to merge. And yes, squash and merge is the preferred way in Lychee so that we can keep a "cleaner" tree.

The behaviour could be sketched out in an issue, or you can use the organisation.

**Pull request merged**
