### PR TITLE
Support for exiftool

### PR DESCRIPTION
**Pull request by tmp-hallenser**
This PR adds support to use Exiftool to extract metadata from images and videos.

1. Adds a new config field 'has_exiftool'
* field initially set to null
* first call determines if exiftool is available 

2. Make use of library PHPExif/php-exif (https://github.com/PHPExif/php-exif/) as a wrapper for Exiftool, FFmpeg and native extraction
* the current latest official version does not support FFmpeg and has other limitations which are currently needed in Lychee
* I enhanced the library such that it's on par with todays exif features of Lychee and created an PR to the official repo
* Suggestion until PR is approved:
(A) Use my fork of the library
(B) Transfer my fork to LycheeOrg and use this one (suggested)

### CODE REVIEW

**Comment by ildyria** [comment]
I merged master in the branch to solve conflicts. I also updated the `.php_cs` so it does not remove the `@param`.

Tested with pictures with and without EXIF data, both with the exiftool and without. Worked in all cases.

Good for merge IMHO.

**Comment by ildyria** [comment]
It would be interesting to see if this PR fixes https://github.com/LycheeOrg/Lychee-Laravel/issues/396

**Comment by d7415** [comment]
> Looks good to me. Tested with exiftool enabled and disabled. Both worked, do not have complains.
> @kamil4 @d7415 last review ?

I don't have time to look at anything this big, but at a very brief skim I don't have any major concerns.

Do we want to stick with @tmp-hallenser's fork, or bring it in-house? As we're just waiting for acceptance upstream I don't mind - it may be less friction to use it as-is. Actually...

**Comment by ildyria** [comment]
> Do we want to stick with @tmp-hallenser's fork, or bring it in-house? As we're just waiting for acceptance upstream I don't mind - it may be less friction to use it as-is.

By fork, you mean the exif reader? I will let @tmp-hallenser decide on that one. Transferring the repo to LycheeOrg may release him from the charge to keep it up to date.

Ideally his changes should be merged in the original https://github.com/PHPExif/php-exif :)

**Comment by d7415** [comment]
> I will let @tmp-hallenser decide on that one.

Makes sense

> Ideally his changes should be merged in the original https://github.com/PHPExif/php-exif :)

Agreed

**Comment by tmp-hallenser** [comment]
I‘ve submitted a PR to the original repo, let‘s see if it’s still active and the PR gets merged (should fulfill all requirements re formatting and testing).

I‘d vote for a migration to Lychee for two reasons: (1) original repo has been quite inactive leaving the hypothesis that it’s not actively maintained anymore (2) in case of bugs, it does not all depend on me (test coverage is close to 100%, but you never know)

**Comment by tmp-hallenser** [comment]
I've moved the php-exif fork to LycheeOrg. 
Unless there are any other objections, the PR should be ready for a merge.

**Pull request merged**
