### PR TITLE
Add try catch around the read extraction, update php-exif [composer install].

### LINKED ISSUE #419: Upload photo - Internal server error
### Detailed description of the problem
After latest upgrade of Lychee (git pull) I can not upload any photo, I only get error: "Server returned an unknown response." In the Diagnostics log everything looks fine, also no errors in the Logs are shown.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any album
2. Click on + and choose Upload Photo
3. Select a photo in the file browser
4. Upload Failed

**Screenshots**

image

### Output of the diagnostics

 Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      f10b4f1 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.3.20-MariaDB
    
    Lychee total space:        507.60 MB
    Upload folder space:       451.74 MB
    System total space:        105.20 GB
    System free space:         85.81 GB (81%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         1
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        description
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    1
    image_overlay:             1
    image_overlay_type:        exif
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           1
    Mod_Frame:                 0
    Mod_Frame_refresh:         30
    landing_page_enable:       0
    landing_owner:             Andrej Valencic
    landing_title:             A V
    landing_subtitle:          These are my photos!
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            https://www.flickr.com/JohnSmith
    landing_twitter:           https://www.twitter.com/JohnSmith
    landing_instagram:         https://instagram.com/JohnSmith
    landing_youtube:           https://www.youtube.com/JohnSmith
    landing_background:        dist/cat.jpg
    thumb_2x:                  1
    small_2x:                  0
    medium_2x:                 0
    site_title:                Lychee v4
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    public_search:             0
    additional_footer_text:    
    display_social_in_gallery: 0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              1
    share_button_visible:      0

### Browser and system
Server Fedora 31
Client Windows 10, Vivaldi or Firefox latest browser

Console output:

main.js?1577525663:7846 POST http://www.sever.lan/Lychee/public/api/Photo::add 500 (Internal Server Error)
process @ main.js?1577525663:7846
(anonymous) @ main.js?1577525663:7867
n @ main.js?1577525663:20
upload.show @ main.js?1577525663:7662
local @ main.js?1577525663:7864
(anonymous) @ main.js?1577525663:3056
dispatch @ main.js?1577525663:2
v.handle @ main.js?1577525663:2
main.js?1577525663:3977 {description: "Upload failed. Server returned an unkown error!", params: XMLHttpRequest, response: ""}
lychee.error @ main.js?1577525663:3977
xhr.onload @ main.js?1577525663:7795
load (async)
process @ main.js?1577525663:7741
(anonymous) @ main.js?1577525663:7867
n @ main.js?1577525663:20
upload.show @ main.js?1577525663:7662
local @ main.js?1577525663:7864
(anonymous) @ main.js?1577525663:3056
dispatch @ main.js?1577525663:2
v.handle @ main.js?1577525663:2

### PR DESCRIPTION
**Pull request by ildyria**
@SerenaButler noticed problems when `has_exiftool` is `1` and `exiftool` is installed and in the path `/usr/bin` thus findable via `which`

The problem is that `which` is not a `sh` command which may be the shell used by some php installations (not debian/ubuntu). This PR updates the composer.lock to update to the updated version of php-exif with the fix.

However this requires the user to do a `composer install`. As we may not be sure this is the case and want to fix the bug even if composer install is not done, I added a try catch. In case of exception, we read the picture again with the default php_exif library.

Nota: Did not check failure cases for the video.

Fixes #419 hopefully.

### CODE REVIEW

**Comment by tmp-hallenser** [comment]
Looks good to me. 
But, does it fix the root cause or does the try-catch only fix the symptom? I understood that the upload fails only on some images (i.e. I'd assume the issue can't be related to the which statement).

Fix for videos would also be need here: https://github.com/LycheeOrg/php-exif/blob/master/lib/PHPExif/Adapter/FFprobe.php

**Comment by ildyria** [comment]
>  does it fix the root cause

Hopefully, I already fixed it for the : https://github.com/LycheeOrg/php-exif/commit/1e991f2b0f95c4fcb8374b077bada70ecf137a30
:smiley: 

Actually, I just tested, I think we should replace `which` by `command -v`.

**Comment by tmp-hallenser** [comment]
We should then also fix these lines:
https://github.com/LycheeOrg/Lychee-Laravel/blob/e339b273fc798cdccc714ecba41887eceb5b8863/app/Configs.php#L264
https://github.com/LycheeOrg/Lychee-Laravel/blob/e339b273fc798cdccc714ecba41887eceb5b8863/database/migrations/2020_01_04_1200_config_has_ffmpeg.php#L29
https://github.com/LycheeOrg/Lychee-Laravel/blob/3626829fc0fcb570abef87b3db6eb09af978a5d4/database/migrations/2019_12_25_0600_config_exiftool_ternary.php#L29

**Comment by ildyria** [comment]
Fixes #419 hopefully.

**Comment by ildyria** [comment]
@tmp-hallenser done in the last commit.

**Pull request merged**
