### PR TITLE
Public recent

### LINKED ISSUE #176: Option to make "Recents" folder public
For now, other (unregistered) users have no tools to track albums. No RSS, no other streams and if there are sub-albums, even with "sort-by-date" - need to go into each and check if there is anything new on top.
As admin user we have "smart-album" called "Recent", it holds latest uploaded photos automatically. But it's not public and no option to make it public.
Maybe add option (may be available in "Settings -> More" option, to keep settings GUI unmodified) to make it public and "days for recent" configurable?
This would allow people to "follow" albums.

### PR DESCRIPTION
**Pull request by kamil4**
fixes #176.

Adds support for public Recent and configurable recent age.

Also fixes a related Search issue where password-protected subalbums would not be included in results. Commentary was improved to better explain what is happening there.

I did not create a new SmartAlbums category because I didn't think it was worth it for just two entries. Maybe make it a part of a future comprehensive cleanup in that area?

### CODE REVIEW

**Comment by kamil4** [comment]
For the sake of completeness: fixes #176. Front end side is in https://github.com/LycheeOrg/Lychee-front/pull/123.

**Comment by kamil4** [comment]
Public Starred support added, as per #47.

Note that this branch touches some of the same code as https://github.com/LycheeOrg/Lychee-Laravel/tree/image_protection. Manual rebasing will be needed on whichever goes second...

**Comment by kamil4** [comment]
With the refactored infrastructure it was really easy to fix the leaks in `getRandom` so I pushed that as well. This was hopefully the last new feature on this branch :smiley:.

**Comment by ildyria** [comment]
Rebased on master. Advised:
```
git checkout master
git branch -D public-recent
git fetch
git pull
git checkout public-recent
```

**Comment by d7415** [comment]
Skim read. Looks good!

**Pull request merged**
