### PR TITLE
Add Italian Translation

### PR DESCRIPTION
**Pull request by edoaxyz**
@ildyria here you have it

### CODE REVIEW

**Comment by d7415** [comment]
Thanks for this. Some keys are still missing. I'm not sure what you used as your source, but I *think* [English.php](https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Locale/English.php) is the most complete.Standing out are `'SEARCH'` and `'MORE'`, but there are probably more. Once they're all present, the Travis tests should pass.

**Comment by d7415** [comment]
> I'm not sure what you used as your source,

Ah, looking at history, maybe the v3 code...

**Comment by edoaxyz** [comment]
I've used [this](https://github.com/LycheeOrg/Lychee/blob/master/php/Locale/English.php) one as source

**Comment by ildyria** [comment]
@edoaxyz if you installed with `composer install` instead of `composer install --no-dev` you have access to  `phpunit` which you can launch via `vendor/bin/phpunit`.
It is pretty usefull to see where things are missing. :)

**Pull request merged**
