### PR TITLE
feat: add share_button_visible option

### PR DESCRIPTION
**Pull request by YoshinoriN**
## Description

I have already read https://github.com/LycheeOrg/Lychee/issues/293. I have the same opinion with [@CountCypher](https://github.com/LycheeOrg/Lychee/issues/293#issuecomment-533881993). 

I want to publish my photo with public permission but I don't want the lychee to appear the share button.
Yes, I can delete that element if I edit & build https://github.com/LycheeOrg/Lychee-front. But, 
I don't want to do it. Because, if I fork it I have to sync upstream with my forked repo.

## Implementation

I implemented this option naming to `sharable`. It behaves just like downloadable. 
The current public album & photo will be `sharable = true` automatically when migrate the database.

## Others 

Maybe I can't backport to this feature to less than [v4](https://github.com/LycheeOrg/Lychee).

Thank you :)

### CODE REVIEW

**Comment by ildyria** [comment]
I would change the wording.
"Visitors of your gallery can share this album."

It is untrue that you are preventing the sharing if you untick the box.

I would say something more in the like "display social media sharing links".

I think you are missing 
```php
define(BOOL, '0|1');
```
in your migration file.

**Comment by YoshinoriN** [comment]
@ildyria 
Thank you :)
I was just about to fix `define(BOOL, '0|1');`.

> I would change the wording.
> It is untrue that you are preventing the sharing if you untick the box.

OK. 
I will change all of `sharable` (database value, variable name, etc) to another naming as well.

**Comment by YoshinoriN** [comment]
@ildyria 
I updated PR and add some fixes.

* `sharable` to `share_button_visible`
    * I was wondering whether to use the word `visibility`. However, I think visibility can take values other than bool(true, false), So, I decide to use `visible`
* Return `share_button_visible` from PhotoController.
    * I forgot to update PhotoController when I first time submitted this PR
* Update all languages explanation.
    * Just copy English
    *  Should I translate all language using by Google Translate?

As you notice my English is not good. Please tell me if you come up with better naming. I will update again and again :)

## Screenshots

sb1

sb2

sb3

## Othres

Should I squash and force push?

Thank you :)

**Comment by ildyria** [comment]
> Should I squash and force push?

No need, we usually directly "Squash and merge" the PR. :)

**Comment by ildyria** [comment]
I'm working on tmp-hallenser PR and then I'll look at yours. :+1:

**Pull request merged**
